[package]
org = "ballerina"
name = "ai_tests"
version = "1.9.2"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ai-native"
version = "1.9.2"
path = "../native/build/libs/ai-native-1.9.2-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ai-native"
version = "1.9.2"
path = "../native/build/libs/ai-native-1.9.2-SNAPSHOT-tests.jar"
testOnly = true
