[plugin]
id = "ai-compiler-plugin"
class = "io.ballerina.stdlib.ai.plugin.AiCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai-compiler-plugin-1.8.0-SNAPSHOT.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-2.3.2.jar"
